### ISSUE TITLE
“sudo docker build -t eventuate-chaos/sbt .” occur some problem

### ISSUE THREAD

**Issue by netcomm** [RBMHTechnology/eventuate-chaos#8]
hi @krasserm , i build docker image use "sudo docker build -t eventuate-chaos/sbt .', but have some network problems, the log is:

Step 7 : RUN cd /app && sbt test:compile && rm build.sbt
 ---> Running in 51466d0e769a
[info] Set current project to eventuate-chaos (in build file:/app/)
[info] Updating {file:/app/}app...
[info] Resolving org.scala-lang#scala-library;2.11.7 ...
[warn] Host central.maven.org not found. url=http://central.maven.org/maven2/org/scala-lang/scala-library/2.11.7/scala-library-2.11.7.pom
[info] You probably access the destination server through a proxy server that is not well configured.

my host network is ok, so i can run "RUN wget -nv "http://downloads.typesafe.com/scala/2.11.7/scala-2.11.7.deb" && \" ok, but when i do sbt something , the network problem is occur,maybe i should use some proxy.
my use vmware to run Ubuntu 14.04, any suggest is appreciate!

**Comment by kongo2002** [comment]
Hi,

as far as I can see the problem does not appear to be related with the _eventuate-chaos_ specific docker scenario at all. The warning says `Host central.maven.org not found` which might indicate some DNS problems in your setup. Maybe it was even a server temporarily not being reachable..?

Cheers,
Gregor

**Comment by krasserm** [comment]
@netcomm any progress on this?

**Comment by netcomm** [comment]
it is ok now, thanks guys!
